### PR TITLE
Demo review changes

### PR DESCRIPTION
**Pull request by kswenson**
Address issues that arose during demo/planning meeting and testing:
- Use Unicode arrow for sorting menu options ("A → Z" instead of "A => Z")
- Fix recent score computation for students with fewer than three challenges completed
  - the code was treating uncompleted challenges as blue crystals
- Use firstName/lastName from portal when available
- Handle case when portal offerings call encounters error and returns no students
  - This was encountered while testing after portal connection timed out
- Fix initial sizing bug which prevented scrolling initially
  - switch from no-longer-maintained ReactDimensions to ReactSizeMe

Testable at https://geniventure-dashboard.concord.org/branch/demo-review/?fake.

### CODE REVIEW

**Comment by kswenson** [comment]
Ah, good to know some of the history. I'll mention that in the PT story. The net effect, however, was that not having completed any challenges was treated as having achieved three blue crystals, so those with no progress at all were sorted just behind those with perfect scores due to the 5% weight to overall progress.

**Comment by sfentress** [comment]
Ah, yes. If you want best recent score at the top, one blue gem should be sorted near the top, but zero gems shouldn't be.

It's still a little odd, though. The initial intent of the "struggling" category was always to put those who were having recent difficulties at the top (so the teacher could seek them out and help them). Now won't this put all the students with zero gems at the top? That seems counter-productive to the intent of the sorting. (If a teacher wanted to see all the student who were furthest behind, they could sort by progress.)

**Comment by sfentress** [comment]
(Note that I think part of our difficulty is now due to the fact that you can sort the "struggling students" category, and so it's drifting away from "here are the kids you should attend to immediately".)

**Comment by kswenson** [comment]
Good points -- I'll raise them with the team. Just looking at the results, the new sort seems more useful to me, but my opinion isn't the important one here.

**Pull request merged**
